<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_x</name>
   <tag></tag>
   <elementGuidId>2ce5d904-1cc4-42d1-93e4-facd0fa25e8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#close-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='close-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aec4c44e-9c94-4a8c-9922-dc930769980f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>CLOSE</value>
      <webElementGuid>13010963-56d9-4f5b-8ee3-0bd57c0bb56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>11cb58a0-6896-4f04-bae7-af5a7a810256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close close-icon moe-inapp-close moe-element</value>
      <webElementGuid>f013c59f-6350-4f6b-b872-bf159ef58c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>58000cf3-5153-4233-ae90-db158f395214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close-icon</value>
      <webElementGuid>de93afc2-ed22-47b2-8c77-4304eb2b8860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> x </value>
      <webElementGuid>9d7a5e20-1de7-4a9c-b6fc-42861445cdef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-icon&quot;)</value>
      <webElementGuid>8c51609d-8073-471e-96fb-49af2b276797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/WebTesting/Page_Homepage/iframe_Allow_moe-onsite-campaign-6497ee380b_382cf9</value>
      <webElementGuid>1d11d9c1-3167-41fb-8e39-a7ea154fec3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='close-icon']</value>
      <webElementGuid>833e4e06-71f6-437a-9896-5f25c3203911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'close-icon', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>033f40d8-bc4a-47e2-bbe0-b637ed00a8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='x']/parent::*</value>
      <webElementGuid>f20b3474-2ef8-4c3c-a313-2bf65a074bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>7b3c885e-603a-49ca-8474-ea7123e92b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'close-icon' and (text() = ' x ' or . = ' x ')]</value>
      <webElementGuid>9963ac96-f583-42df-a8a6-5fdb4a997d22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
