<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_product</name>
   <tag></tag>
   <elementGuidId>2cdcda26-7376-4492-9131-48f91574d2ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='homepagePromoBrandProductName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#homepagePromoBrandProductName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ddade1b8-9b76-4fcd-8821-8a46fa3f257a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product__name</value>
      <webElementGuid>809ed287-1282-4c47-ae96-cc263ebd6061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>homepagePromoBrandProductName</value>
      <webElementGuid>c238425d-7a37-482d-af2c-fd3ff5a830af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Arthome Tanaman Artifisial Succulent Mix In Shaw Pot B</value>
      <webElementGuid>4423dd93-b52d-48ee-9bc3-db0ce17d0204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;container container__desktop&quot;]/div[1]/section[3]/div[@class=&quot;row flex&quot;]/div[@class=&quot;col-xs-10 padding-left-xs padding-top-m&quot;]/div[@class=&quot;row__wrappers padding-top-xl&quot;]/div[@class=&quot;row product-card&quot;]/div[@class=&quot;content__product&quot;]/div[@id=&quot;productsCarousel&quot;]/a[@id=&quot;productsProductCard&quot;]/div[@class=&quot;row middle-xs&quot;]/div[@class=&quot;col-xs-12 margin-top-xs&quot;]/span[@id=&quot;homepagePromoBrandProductName&quot;]</value>
      <webElementGuid>4d3d89f1-15b7-44d3-91f8-1c8c8bb527e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='homepagePromoBrandProductName']</value>
      <webElementGuid>3fd55a9f-9d15-4a9c-8a32-771bbe6260c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='productsProductCard']/div/div[2]/span</value>
      <webElementGuid>54698faf-e5a7-40f2-b5af-13d50e7c459c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diskon Tertinggi'])[1]/following::span[2]</value>
      <webElementGuid>518eb542-bae8-4068-82bc-e906d91ff5ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga Tertinggi'])[1]/following::span[3]</value>
      <webElementGuid>6a118d78-a5c2-4f13-a868-130d57bef136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp249.900'])[4]/preceding::span[1]</value>
      <webElementGuid>f8527f14-9685-4b81-a9fc-7c6f62697b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy 1 Get 1'])[2]/preceding::span[1]</value>
      <webElementGuid>a1e3e91b-c4da-4e62-b127-ce60f8425e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div[2]/span</value>
      <webElementGuid>83f2a16d-73ff-4a54-aa16-1188ccb09d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'homepagePromoBrandProductName' and (text() = 'Arthome Tanaman Artifisial Succulent Mix In Shaw Pot B' or . = 'Arthome Tanaman Artifisial Succulent Mix In Shaw Pot B')]</value>
      <webElementGuid>7754f4d1-78b1-4cee-8cac-fff347d718c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
